-- English dialogue shots are filmed with the voice generated by the video
-- model itself (no TTS, no lip-sync pass). The flag tells the finishing
-- stages and the stitch to take the speech from the filmed clip.
ALTER TABLE series_shots ADD COLUMN native_audio INTEGER DEFAULT 0;
