// ============================================
// GENESIS BRAIN — Audio Engine
// Voiceover, Music, Captions generation
// ============================================

import { VoiceoverTiming } from "@/types";
import { BUILT_IN_AUDIO_TRACKS } from "@/lib/constants";

export interface AudioResult {
  type: "voiceover" | "music" | "captions";
  url: string;
  duration: number;
  metadata?: Record<string, unknown>;
}

export interface CaptionEntry {
  index: number;
  startTime: string; // SRT format: HH:MM:SS,mmm
  endTime: string;
  text: string;
}

// ---- VOICEOVER GENERATION ----

/**
 * Generate voiceover using Edge TTS (Microsoft) — free, 300+ voices
 * Falls back to a simple audio placeholder if Edge TTS is unavailable
 */
export async function generateVoiceover(
  script: string,
  language: string = "en-US",
  voice?: string,
  timings?: VoiceoverTiming[]
): Promise<AudioResult> {
  if (!script || script.trim().length === 0) {
    throw new Error("Voiceover script cannot be empty");
  }

  // Select voice based on language
  const voiceId = voice || getDefaultVoice(language);

  // For production: use Edge TTS via RunPod worker or external API
  // Edge TTS is free and supports 300+ voices in 75+ languages
  //
  // API call pattern:
  // POST to a TTS endpoint (self-hosted or external)
  // Input: { text, voice, language, rate, pitch }
  // Output: { audio_url, duration_seconds, word_timestamps }

  const ttsEndpoint = process.env.TTS_ENDPOINT_URL;

  if (ttsEndpoint) {
    try {
      const response = await fetch(ttsEndpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: script,
          voice: voiceId,
          language,
          rate: "+0%",
          pitch: "+0Hz",
          output_format: "mp3",
        }),
      });

      if (response.ok) {
        const data = await response.json();
        return {
          type: "voiceover",
          url: data.audio_url,
          duration: data.duration || estimateVoiceoverDuration(script),
          metadata: { voice: voiceId, language, wordTimestamps: data.timestamps },
        };
      }
    } catch (err) {
      console.warn("[BRAIN AUDIO] TTS endpoint failed, using estimation:", err);
    }
  }

  // Fallback: return metadata without actual audio (generation happens in assembly worker)
  // The assembly worker will use its own TTS capabilities
  return {
    type: "voiceover",
    url: "", // Will be generated by assembly worker
    duration: estimateVoiceoverDuration(script),
    metadata: {
      script,
      voice: voiceId,
      language,
      timings: timings || [],
      generateInAssembly: true, // Flag for assembly worker to handle TTS
    },
  };
}

/**
 * Estimate voiceover duration based on word count
 * Average speaking rate: ~150 words per minute
 */
function estimateVoiceoverDuration(script: string): number {
  const words = script.trim().split(/\s+/).length;
  return Math.ceil((words / 150) * 60);
}

/**
 * Get default voice for a language
 */
function getDefaultVoice(language: string): string {
  const voiceMap: Record<string, string> = {
    "en-US": "en-US-GuyNeural",
    "en-GB": "en-GB-RyanNeural",
    "es-ES": "es-ES-AlvaroNeural",
    "fr-FR": "fr-FR-HenriNeural",
    "de-DE": "de-DE-ConradNeural",
    "it-IT": "it-IT-DiegoNeural",
    "pt-BR": "pt-BR-AntonioNeural",
    "ja-JP": "ja-JP-KeitaNeural",
    "ko-KR": "ko-KR-InJoonNeural",
    "zh-CN": "zh-CN-YunxiNeural",
    "hi-IN": "hi-IN-MadhurNeural",
    "ar-SA": "ar-SA-HamedNeural",
    "zu-ZA": "zu-ZA-ThandoNeural",
    "af-ZA": "af-ZA-WillemNeural",
  };
  return voiceMap[language] || "en-US-GuyNeural";
}

// ---- MUSIC SELECTION / GENERATION ----

/**
 * Select or generate background music
 */
export async function selectMusic(
  mood: string,
  tempo: "slow" | "medium" | "fast",
  duration: number,
  genre?: string
): Promise<AudioResult> {
  // Strategy: Match from built-in royalty-free library first
  // If no match, use generic ambient track

  const moodLower = mood.toLowerCase();
  const tempoMap = { slow: [60, 90], medium: [90, 130], fast: [130, 180] };
  const [minBpm, maxBpm] = tempoMap[tempo] || [90, 130];

  // Find best matching track from library
  let bestTrack = BUILT_IN_AUDIO_TRACKS.find((t) => {
    const genreMatch = !genre || t.genre.toLowerCase().includes(genre.toLowerCase());
    const moodMatch = moodLower.split(" ").some((word) =>
      t.name.toLowerCase().includes(word) || t.genre.toLowerCase().includes(word)
    );
    const bpmMatch = !t.bpm || (t.bpm >= minBpm && t.bpm <= maxBpm);
    return (genreMatch || moodMatch) && bpmMatch;
  });

  // Fallback: pick by genre alone
  if (!bestTrack) {
    bestTrack = BUILT_IN_AUDIO_TRACKS.find((t) =>
      t.genre.toLowerCase().includes(tempo === "slow" ? "ambient" : tempo === "fast" ? "electronic" : "cinematic")
    );
  }

  // Final fallback: first available track
  if (!bestTrack && BUILT_IN_AUDIO_TRACKS.length > 0) {
    bestTrack = BUILT_IN_AUDIO_TRACKS[0];
  }

  if (bestTrack) {
    return {
      type: "music",
      url: bestTrack.url,
      duration: bestTrack.duration,
      metadata: {
        trackName: bestTrack.name,
        genre: bestTrack.genre,
        bpm: bestTrack.bpm,
        needsTrim: bestTrack.duration > duration,
        targetDuration: duration,
      },
    };
  }

  // No tracks available — assembly worker can use its own music library
  return {
    type: "music",
    url: "",
    duration,
    metadata: {
      mood,
      tempo,
      genre: genre || "ambient",
      generateInAssembly: true,
    },
  };
}

// ---- CAPTION GENERATION ----

/**
 * Generate SRT captions from voiceover script and timings
 */
export function generateCaptions(
  script: string,
  timings: VoiceoverTiming[]
): AudioResult {
  if (!script || !timings || timings.length === 0) {
    // Generate timings from script if not provided
    const words = script.trim().split(/\s+/);
    const wordsPerSecond = 2.5;
    const entries: CaptionEntry[] = [];

    let currentTime = 0.5;
    const chunkSize = 8; // words per caption line
    let index = 1;

    for (let i = 0; i < words.length; i += chunkSize) {
      const chunk = words.slice(i, i + chunkSize).join(" ");
      const chunkDuration = (Math.min(chunkSize, words.length - i) / wordsPerSecond);
      const startTime = currentTime;
      const endTime = currentTime + chunkDuration;

      entries.push({
        index,
        startTime: formatSrtTime(startTime),
        endTime: formatSrtTime(endTime),
        text: chunk,
      });

      currentTime = endTime + 0.2; // Small gap between captions
      index++;
    }

    const srtContent = entries
      .map((e) => `${e.index}\n${e.startTime} --> ${e.endTime}\n${e.text}\n`)
      .join("\n");

    return {
      type: "captions",
      url: "", // SRT content is stored as metadata, uploaded during assembly
      duration: currentTime,
      metadata: {
        srtContent,
        captionCount: entries.length,
        entries,
      },
    };
  }

  // Build SRT from provided timings
  const entries: CaptionEntry[] = timings.map((t, i) => ({
    index: i + 1,
    startTime: formatSrtTime(t.startTime),
    endTime: formatSrtTime(t.endTime),
    text: t.text,
  }));

  const srtContent = entries
    .map((e) => `${e.index}\n${e.startTime} --> ${e.endTime}\n${e.text}\n`)
    .join("\n");

  return {
    type: "captions",
    url: "",
    duration: timings[timings.length - 1]?.endTime || 0,
    metadata: {
      srtContent,
      captionCount: entries.length,
      entries,
    },
  };
}

/**
 * Format seconds to SRT timestamp: HH:MM:SS,mmm
 */
function formatSrtTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.round((seconds % 1) * 1000);
  return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")},${ms.toString().padStart(3, "0")}`;
}

// ---- AVAILABLE VOICES ----

export const AVAILABLE_VOICES: Record<string, Array<{ id: string; name: string; gender: string }>> = {
  "en-US": [
    { id: "en-US-GuyNeural", name: "Guy (Natural)", gender: "male" },
    { id: "en-US-JennyNeural", name: "Jenny (Natural)", gender: "female" },
    { id: "en-US-AriaNeural", name: "Aria (Expressive)", gender: "female" },
    { id: "en-US-DavisNeural", name: "Davis (Deep)", gender: "male" },
  ],
  "en-GB": [
    { id: "en-GB-RyanNeural", name: "Ryan", gender: "male" },
    { id: "en-GB-SoniaNeural", name: "Sonia", gender: "female" },
  ],
  "es-ES": [
    { id: "es-ES-AlvaroNeural", name: "Alvaro", gender: "male" },
    { id: "es-ES-ElviraNeural", name: "Elvira", gender: "female" },
  ],
  "fr-FR": [
    { id: "fr-FR-HenriNeural", name: "Henri", gender: "male" },
    { id: "fr-FR-DeniseNeural", name: "Denise", gender: "female" },
  ],
  "zu-ZA": [
    { id: "zu-ZA-ThandoNeural", name: "Thando", gender: "female" },
    { id: "zu-ZA-ThembaNeural", name: "Themba", gender: "male" },
  ],
  "af-ZA": [
    { id: "af-ZA-WillemNeural", name: "Willem", gender: "male" },
    { id: "af-ZA-AdriNeural", name: "Adri", gender: "female" },
  ],
};

export const SUPPORTED_LANGUAGES = [
  { code: "en-US", name: "English (US)" },
  { code: "en-GB", name: "English (UK)" },
  { code: "es-ES", name: "Spanish" },
  { code: "fr-FR", name: "French" },
  { code: "de-DE", name: "German" },
  { code: "it-IT", name: "Italian" },
  { code: "pt-BR", name: "Portuguese (BR)" },
  { code: "ja-JP", name: "Japanese" },
  { code: "ko-KR", name: "Korean" },
  { code: "zh-CN", name: "Chinese (Mandarin)" },
  { code: "hi-IN", name: "Hindi" },
  { code: "ar-SA", name: "Arabic" },
  { code: "zu-ZA", name: "Zulu" },
  { code: "af-ZA", name: "Afrikaans" },
];
